// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg53cdy_TYsGPFWKhruGc7bTtGA3qsLj8',
    appId: '1:112094614554:web:bbfaea9cd311be88ce6da3',
    messagingSenderId: '112094614554',
    projectId: 'chat-app-afa8a',
    authDomain: 'chat-app-afa8a.firebaseapp.com',
    storageBucket: 'chat-app-afa8a.appspot.com',
    measurementId: 'G-JPXXECKF45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeqVM6_jJqivMhU_L_pDSLlsWQG9YxHWM',
    appId: '1:112094614554:android:95147b7f1d98f20bce6da3',
    messagingSenderId: '112094614554',
    projectId: 'chat-app-afa8a',
    storageBucket: 'chat-app-afa8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCITX7Xb-dGrGqIxTMUg4swVZitEyhQz80',
    appId: '1:112094614554:ios:5097d5d341fb279ace6da3',
    messagingSenderId: '112094614554',
    projectId: 'chat-app-afa8a',
    storageBucket: 'chat-app-afa8a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCITX7Xb-dGrGqIxTMUg4swVZitEyhQz80',
    appId: '1:112094614554:ios:5097d5d341fb279ace6da3',
    messagingSenderId: '112094614554',
    projectId: 'chat-app-afa8a',
    storageBucket: 'chat-app-afa8a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg53cdy_TYsGPFWKhruGc7bTtGA3qsLj8',
    appId: '1:112094614554:web:74846b56c7f1b90bce6da3',
    messagingSenderId: '112094614554',
    projectId: 'chat-app-afa8a',
    authDomain: 'chat-app-afa8a.firebaseapp.com',
    storageBucket: 'chat-app-afa8a.appspot.com',
    measurementId: 'G-BQH991SDC0',
  );
}
